Feature/discord server
ModdedMinecraftClub/polychat2 pull request #10
Opened 2020-08-29 12:49 UTC by TraceLD

2020-09-11 04:53 UTC, john01dav requested changes

2020-09-11 04:53 UTC, john01dav commented on server/build.gradle
> +		compile('ch.qos.logback:logback-classic:1.2.3')
Indentation should not be irregular like this, at least within the same code block.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/OnlineServer.java
> +public class OnlineServer {
This looks like a POD type, so it should be final. More generally, all types that don't need to be non-final should be final.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +import club.moddedminecraft.polychat.core.networklibrary.Message;
These imports are *very* disorganized. Imports from the same library should be grouped together, ideally in their own paragraphs.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        jda = JDABuilder.createDefault("") // will need to be retrieved from YAML;
YAML should be implemented prior to this merge

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        generalChannel = jda.getTextChannelById(""); // same as above here;
More YAML

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatMessageBus.java
> +    public void addEventHandler(Object eventHandler) {
addEventHandlers can take one argument, so this function should be removed

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        polychatMessageBus.addEventHandlers(
Great addition with varargs :)

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        } catch (IOException | LoginException | InterruptedException e) {
SLF4J is here due to JDA, so errors should go to it. It's best to do all such logging in a uniform way in a project, at least where it's this easy to do it.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                    net.dv8tion.jda.api.entities.Message discordMsg = ev.getMessage();
Oof..... this is messy, but I don't see what we can do about it.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                    // ignore messages from self and other bots;
Won't this break member bot? (unless, of course, the refactored http request is supposed to be deployed before this is, in which case never mind)

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                    for (OnlineServer server : onlineServers.values()) {
There's a built-in function on Server for this. We don't need to duplicate this loop each time a method is sent. Additionally, a method name is easier to read than a for loop, since a method name is more human-readable.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                new ChatMessageHandler(generalChannel, onlineServers),
I also like that this is split into so many classes, so good single responsibility principle.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ChatMessageHandler.java
> +public class ChatMessageHandler {
Should be final, see previous comment regarding finality; same applies to other message handlers; comment won't be repeated.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ChatMessageHandler.java
> +    private void sendMessageToOtherClients(ChatProtos.ChatMessage msg) {
It would be better if this was based on == comparisons of ConnectedClient objects — sending to all ConnectedClients that don't equal the author, since then it won't break if two servers have the same ID for whatever reason. This should be an easy enough fix, juts pass the author variable to this function and slightly change the loop.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/GenericCommandResultMessageHandler.java
> +            logger.error("Client told me a command was sent from a Discord channel that doesn't exist.");
Do we have support for multiple channels? If not, then just using the given #general channel would likely be better, since it avoids a possible error, and keeps the system simpler (client doesn't need to care about Discord channels).

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PlayerStatusChangedMessageHandler.java
> +            logger.error("Server with id \""
This error message is wonderful

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PlayersOnlineMessageHandler.java
> +    private final static Logger logger = LoggerFactory.getLogger(ServerStatusMessageHandler.class);
Your classes don't match.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PlayersOnlineMessageHandler.java
> +            server.updatePlayersInfo(msg);
It looks like the interpretation of a message class has been removed from a handler and moved into the OnlineServer class. This is questionable, since the OnlineServer's responsibility is to store data, and the message handlers' purpose is to interpret messages.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PromoteMemberCommandHandler.java
> +                    .setDefaultCommand("/ranks add") // TODO: ask 132 if that's the right format;
@132ikl

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ServerInfoMessageHandler.java
> +public class ServerInfoMessageHandler {
This class is :egg: cellent.

2020-09-11 04:53 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ServerStatusMessageHandler.java
> +                onlineServers.remove(serverId);
Don't we need to broadcast this message?

2020-09-11 04:56 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/OnlineServer.java
> +public class OnlineServer {
Java vileness

2020-09-11 04:59 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/GenericCommandResultMessageHandler.java
> +            logger.error("Client told me a command was sent from a Discord channel that doesn't exist.");
We do.

2020-09-11 05:00 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PlayersOnlineMessageHandler.java
> +    private final static Logger logger = LoggerFactory.getLogger(ServerStatusMessageHandler.class);
oopsy

2020-09-13 02:51 UTC, 132ikl commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/PromoteMemberCommandHandler.java
> +                    .setDefaultCommand("/ranks add") // TODO: ask 132 if that's the right format;
without the ! and /

2020-09-29 02:44 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        jda = JDABuilder.createDefault("") // will need to be retrieved from YAML;
implementing yaml last

2020-09-29 02:45 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +        polychatMessageBus.addEventHandlers(
thanks

2020-09-29 03:03 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ServerStatusMessageHandler.java
> +                onlineServers.remove(serverId);
we probably do

2020-09-29 03:03 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/handlers/ServerStatusMessageHandler.java
> +                onlineServers.remove(serverId);
will work on it tomorrow

2020-09-29 03:05 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                    for (OnlineServer server : onlineServers.values()) {
false, it doesn't exist

2020-09-29 03:16 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/core/server/PolychatServer.java
> +                    for (OnlineServer server : onlineServers.values()) {
nvm, it was just stupidly named which is now fixed

2020-10-13 17:36 UTC, closed without merging

2020-10-13 17:36 UTC, 132ikl commented
Superseded by #12