Feature/client base
ModdedMinecraftClub/polychat2 pull request #11
Opened 2020-08-31 02:55 UTC by 132ikl

2020-09-07 19:08 UTC, john01dav requested changes

2020-09-07 19:08 UTC, john01dav commented on client/bukkit-1.7.10/src/main/java/club/moddedminecraft/polychat/client/bukkit1710/Bukkit1710Client.java
> +        ArrayList<String> players = new ArrayList<>();
add an ensureCapacity call to this

2020-09-07 19:08 UTC, john01dav commented on client/bukkit-1.7.10/src/main/java/club/moddedminecraft/polychat/client/bukkit1710/Bukkit1710Client.java
> +package club.moddedminecraft.polychat.client.bukkit1710;
Why is this class different from the Polychat class? You can implement more than one interface in a Java class, and EventListener provides no methods, so no conflicts will occur. This same comment applies to the Forge implementations too. All this does is prevent someone from seeing everything that takes place at the same time.

2020-09-07 19:08 UTC, john01dav commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/OnlinePlayerThread.java
> +    private void run() {
This is not thread-safe, as discussed in Discord.

2020-09-07 19:08 UTC, john01dav commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/PolychatClient.java
> +                config.getOrDefault("poly_address", "localhost"),
Why the "_"? My YamlConfig class uses "." as its separator. It looks like you have a glorified .properties file here.

2020-09-07 19:08 UTC, john01dav commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/PolychatClient.java
> +                config.getOrDefault("poly_buffersize", 32768)
Do we really want this to be configurable? There is a threshold equal to the maximum message size after which everything works, and below which Bad Things™ happen — it would be more user-friendly if users didn't have to worry about this.

2020-09-07 19:08 UTC, john01dav commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/PolychatClient.java
> +public class PolychatClient {
This class is a bit long. It would be best to break it into multiple internal classes, but to keep its usage from the various client implementations the same. One of the split-offs would be to have a `ClientCallbacks` class, where all public methods are callbacks that the client must make (e.g. when a player joins), so that they're all in one place to avoid missing them, and to prevent callbacks that should not be callbacks.

2020-09-07 19:08 UTC, john01dav commented on client/bukkit-1.7.10/src/main/java/club/moddedminecraft/polychat/client/bukkit1710/Polychat.java
> +        getServer().getScheduler().runTaskTimer(this, this::onTick, 0, 1);
Does this need to run *every* tick? I'm not sure, but I think that it doesn't. Probably 4 times per second (every 5 ticks) is more reasonable. This same concern applies to the Forge clients too.

2020-09-07 19:08 UTC, john01dav commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/ClientBase.java
> +public interface ClientBase {
I would call this class `ClientApiBase`, since it is the base for the API that the client uses, and each implementation is a mini-Bukkit-API — not the client itself.

2020-09-07 19:08 UTC, john01dav commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/Polychat.java
> +    public void onTick(TickEvent.ServerTickEvent event) {
To implement something every x ticks, count the elapsed ticks in a variable (or, even better, elapsed time to 250ms), and then call the common client code if enough time and/or ticks have elapsed.

2020-09-07 20:14 UTC, 132ikl commented
Waiting on timer to remove OnlinePlayerThread, waiting for discussion consensus on crash handling before removing shutdown hook

2020-10-10 04:43 UTC, TraceLD requested changes

2020-10-10 04:43 UTC, TraceLD commented on .gitignore
> +# Gradle
I don't know Gradle well, so I will assume you know what you're doing here

2020-10-10 04:43 UTC, TraceLD commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/util/MuteStorage.java
> +    private final String FILENAME = "polychat-mutelist.txt";
I have multiple concerns with this:
1) you're introducing new format, when rest of the program uses YAML
2) you're using a text file like it's a database, since I see write methods. Have you considered issues such as the possibility of two things writing to the file causing potential corruption of data? Even if you have, it still seems like a weird thing to do considering we have MySQL backend.

Even if you change the txt file to YAML and JSON, they were designed to represent data, not for working with data that is dynamically updated.

Overall this whole solution shouts "hacky".

2020-10-10 04:43 UTC, TraceLD commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/MuteCommand.java
> +        return "/pcmute";
I'm not sure how I feel about the name "/pcmute" for this command. It's obvious for us that "pc" means "polychat" but I'm pretty sure most of the playerbase isn't familiar with that, also that abbreviation means "personal computer" to most people which introduces further confusion.

2020-10-10 04:43 UTC, TraceLD commented on core/message-library/src/main/proto/chat.proto
> +message ChatMessage {
I assume that's the new format that we've agreed on?

2020-10-10 04:43 UTC, TraceLD commented on core/network-library/src/main/java/club/moddedminecraft/polychat/core/networklibrary/Client.java
> +    private final ArrayList<byte[]> reconnectMessageSet = new ArrayList<>();
@john01dav did you approve these changes to networking library?

2020-10-10 04:46 UTC, TraceLD commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/OnlinePlayerThread.java
> +    private void run() {
@132ikl did you address this?

2020-10-10 04:47 UTC, TraceLD commented
> Waiting on timer to remove OnlinePlayerThread, waiting for discussion consensus on crash handling before removing shutdown hook

what happened with that?

2020-10-10 05:01 UTC, 132ikl commented on core/network-library/src/main/java/club/moddedminecraft/polychat/core/networklibrary/Client.java
> +    private final ArrayList<byte[]> reconnectMessageSet = new ArrayList<>();
Yes, he did (after much complaining)

2020-10-10 05:02 UTC, 132ikl commented
@TraceLD 
> Waiting on timer to remove OnlinePlayerThread

never happened
> waiting for discussion consensus on crash handling before removing shutdown hook

we decided that server would handle crash handling, but I never actually removed the hook

2020-10-10 05:02 UTC, 132ikl commented on core/message-library/src/main/proto/chat.proto
> +message ChatMessage {
Yes

2020-10-10 05:02 UTC, 132ikl commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/MuteCommand.java
> +        return "/pcmute";
What do you propose as an alternative? `/mute` is already taken by FTBU.

2020-10-10 05:05 UTC, 132ikl commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/util/MuteStorage.java
> +    private final String FILENAME = "polychat-mutelist.txt";
1. No more data needs to be stored than the username, so YAML is excessive.
2. We could hook into the MySQL backend, but that seems extremely excessive for anyone who isn't us (which we know there are people who use polychat which are not us). Two things should never be writing to the file at once. Making more than one instance of MuteStorage is undefined behavior. We can enforce that if you'd really like.

2020-10-10 05:06 UTC, 132ikl commented on .gitignore
> +# Gradle
I just copied this from github/gitignore

2020-10-10 05:06 UTC, 132ikl commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/OnlinePlayerThread.java
> +    private void run() {
This is what the timer was going to fix

2020-10-10 05:21 UTC, TraceLD commented on core/message-library/src/main/proto/chat.proto
> +message ChatMessage {
Ok

2020-10-10 05:21 UTC, TraceLD commented on core/network-library/src/main/java/club/moddedminecraft/polychat/core/networklibrary/Client.java
> +    private final ArrayList<byte[]> reconnectMessageSet = new ArrayList<>();
Ok.

2020-10-10 05:22 UTC, TraceLD commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/util/MuteStorage.java
> +    private final String FILENAME = "polychat-mutelist.txt";
What happens if 2 people request mute at the exact same time? @132ikl

2020-10-10 05:22 UTC, TraceLD commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/MuteCommand.java
> +        return "/pcmute";
/chatmute? Seems kinda long, idk

2020-10-10 05:23 UTC, TraceLD commented
> 
> 
> @TraceLD
> 
> > Waiting on timer to remove OnlinePlayerThread
> 
> never happened
> 
> > waiting for discussion consensus on crash handling before removing shutdown hook
> 
> we decided that server would handle crash handling, but I never actually removed the hook

Should the hook be removed before merging or no? @132ikl

2020-10-12 15:37 UTC, 132ikl commented
No, because the timer was never implemented. Until it is the OnlinePlayerThread must stay.

2020-10-12 15:37 UTC, 132ikl commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/MuteCommand.java
> +        return "/pcmute";
eh

2020-10-12 15:39 UTC, 132ikl commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/util/MuteStorage.java
> +    private final String FILENAME = "polychat-mutelist.txt";
All command events are fired on the main thread (as far as I'm aware) so it's not possible for 2 people to request mute at the exact same time. Calling MuteStorage from multiple threads is undefined behavior. I can add a comment about this if necessary. The very very worst case scenario is that the mute list is entirely reset which really isn't that big of a deal, and I cannot think of scenario where that would actually happen.

2020-10-13 03:11 UTC, TraceLD commented on client/client-base/src/main/java/club/moddedminecraft/polychat/client/clientbase/util/MuteStorage.java
> +    private final String FILENAME = "polychat-mutelist.txt";
Ok, let's keep it as it is then and if problems arise we will re-evaluate.

2020-10-13 03:12 UTC, TraceLD commented on client/forge-1.12.2/src/main/java/club/moddedminecraft/polychat/client/forge1122/MuteCommand.java
> +        return "/pcmute";
Since there are no good suggestions for a different name, lets keep it.

2020-10-13 03:12 UTC, TraceLD commented
> 
> 
> No, because the timer was never implemented. Until it is the OnlinePlayerThread must stay.

Ok, I'm merging this PR and once you/john get around to making the timer you can make a separate feature branch.

2020-10-13 03:13 UTC, TraceLD approved these changes

2020-10-13 03:13 UTC, merged

2020-10-13 03:20 UTC, 132ikl commented
FINALLY