feature/promote retries
ModdedMinecraftClub/polychat2 pull request #34
Opened 2021-01-12 02:22 UTC by TraceLD

2021-01-12 04:22 UTC, john01dav commented
Overall, this is a very good change, but I see two concerns:

- In Java, IInterface isn't the standard, so ITickableServic should be renamed. 
- This might be over-engineering, but it would be cleaner and more reusable to refactor the every x ticks logic from the broadcast service into an abstract class that implements TickableService. Said class would have a final implementation of tick() and an abstract method with a name like onRun() or something.

2021-01-12 04:23 UTC, john01dav requested changes
See my previous comment (it didn't register as a review in Github for some reason).

2021-01-12 05:00 UTC, john01dav requested changes

2021-01-12 05:00 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/server/services/BroadcasterService.java
> +    public static final int INTERVAL_IN_TICKS = (10 * 60 * 20);
While we're here, there should probably be a comment saying that this is 10 mintues (at least, I think that it is, hence the need for a comment).

2021-01-12 05:00 UTC, john01dav commented on server/src/main/java/club/moddedminecraft/polychat/server/services/TimedTickableService.java
> +    public void onRun() {}
This should be `public abstract void onRun();`.

2021-01-12 05:02 UTC, TraceLD commented on server/src/main/java/club/moddedminecraft/polychat/server/services/BroadcasterService.java
> +    public static final int INTERVAL_IN_TICKS = (10 * 60 * 20);
I honestly have no clue. This interval was agreed on months ago.

2021-01-12 05:09 UTC, john01dav approved these changes

2021-01-12 05:09 UTC, merged

2021-01-12 17:19 UTC, 132ikl commented on server/src/main/java/club/moddedminecraft/polychat/server/services/BroadcasterService.java
> +    public static final int INTERVAL_IN_TICKS = (10 * 60 * 20);
10s*60s = 600s * 20t = 12000 ticks = 10 mins

2021-01-12 17:20 UTC, john01dav commented
Did you verify that it's 20 ticks per second?

On Tue, Jan 12, 2021, 11:19 AM 132ikl <notifications@github.com> wrote:

> *@132ikl* commented on this pull request.
> ------------------------------
>
> In
> server/src/main/java/club/moddedminecraft/polychat/server/services/BroadcasterService.java
> <https://github.com/ModdedMinecraftClub/polychat2/pull/34#discussion_r555942251>
> :
>
> >      private int broadcastMsgsIndex;
>
> -    public static final int BROADCAST_EVERY_X_IN_TICKS = (10 * 60 * 20);
> +    public static final int INTERVAL_IN_TICKS = (10 * 60 * 20);
>
> 10s*60s = 600s * 20t = 12000 ticks = 10 mins
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/ModdedMinecraftClub/polychat2/pull/34#discussion_r555942251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA6MJIMF24VA3MPTYJJYOTDSZSADFANCNFSM4V6QJFTA>
> .
>

2021-01-13 16:47 UTC, 132ikl commented
It is

https://github.com/ModdedMinecraftClub/polychat2/blob/master/server/src/main/java/club/moddedminecraft/polychat/server/PolychatServer.java#L38